config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root "pages#index"
  get "about", :to => "pages#about", :as => "about"
  get "place", :to => "pages#place", :as => "place"
  
  get 'login',    :to => 'sessions#new',      :as => 'login'
  get 'logout',   :to => 'sessions#destroy',  :as => 'logout'
  post 'sessions', :to => 'sessions#create',  :as => 'sessions'

  resources :users do
    resources :tasks do
      resources :tags, :only => [:create, :destroy]
        collection do
          get "unclosed"
        end

        member do
          put "done"
        end
    end
  end
  

  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    validates :name, :presence => true, :uniqueness => true
    has_many :taggings
    has_many :tasks, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
     belongs_to :tag
     belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
    
 belongs_to :user
 
 #STEp11-5で追加
 has_many :taggings
 has_many :tags, :through => :taggings
    
    scope :closed,      lambda { where(:status => true) }
    scope :unclosed,    lambda { where.not(:status => true) }
    scope :recently,    lambda { where("deadline <= ?", 3.days.since) }
    scope :search,      lambda { |name| where("name like ?", "%#{name}%") if name.present? }
    
    #STEp11-10で追加
    scope :by_tag,      lambda {|tag| includes(:tags).where(:tags => {:name => tag}) if tag.present? }    

    validates :name, :presence => true, :uniqueness => {:scope => :user_id}
    validates :status, :inclusion => [true, false]
    
    # リマインド通知機能実装前1/3　validates :deadline, :presence => true
    # 試しに戻してみる　validates :deadline, :presence => true, if: :need_reminder?
    validates :deadline, :presence => true
    
    # リマインド通知機能2/3　24時間以内のToDoならtrueを返す。
    def todays_todo?
    # if !deadline.nil?
       deadline < Time.now.since(24.hours) && deadline >= Time.zone.now
    # end
    end
     
    # private
    ## リマインダ通知機能3/3heroku addons:create scheduler:standardがtrueの時はstatusを必須とする
    #def need_reminder?
    #  status == false
    #end
end

app/models/user.rb
class User < ActiveRecord::Base
 before_create :encrypted_password
 
 has_many :tasks, :dependent => :destroy
 
 validates :name, :presence => true
 validates :email, :presence => true, :uniqueness => true
 
 validates :password, :presence => true, :confirmation => true
 
 def self.authenticate(email, password)
  find_by_email_and_password(email, Digest::SHA1.hexdigest(password))
 end
 
 private
 def encrypted_password
  self.password = Digest::SHA1.hexdigest(self.password)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #STEp10-8追加
  helper_method :current_user
  
  #STEp10-10追加
  before_action :login_required
  
 private
 def current_user
   if session[:user_id]
      @login_user ||= User.find_by(:id => session[:user_id])
   end
 end
 
 def login_required
   unless current_user
    flash[:alert] = "ログインしてください"
    redirect_to login_path
   end
 end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :login_required
  
  def index
  end
  
  def about
  end
  
  def place
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, :only => [:new, :create]
  
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:alert] = "ログインに失敗しました"
      render :action => 'new'
    end
  end
  
  def destroy
    reset_session
    flash[:alert] = "ログインしました"
    redirect_to login_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_task, :find_user
  
  def create
    unless params[:name].blank?
      tag = Tag.find_or_create_by(name: params[:name])
      @task.tags << tag unless @task.tags.find_by(:id => tag.id)
    end
    redirect_to user_task_path(@user, @task)
  end
  
  def destroy
    tag = Tag.find(params[:id]) 
    @task.tags.destroy(tag)
    unless tag.tasks.any?
      tag.destroy
    end
      redirect_to user_task_path(@user, @task)
  end

  private
  def find_task
    @task = Task.find(params[:task_id])
  end
  
  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_user
  before_action :find_task, :only => [:show, :edit, :update, :destroy, :done]
  
  def index
    # @task = Task.all
    @name = params[:name]
    #STEp11-10で追加 @tasks = @user.tasks.search(@name)
    @tasks = @user.tasks.search(@name).by_tag(params[:tag])
  end

  def show
  end

  def new
    @task = @user.tasks.build(:status => false)
  end

  def edit
  end
  
  def create
    @task = @user.tasks.build(task_params)
    
    if @task.save
      redirect_to user_tasks_path(@user,@task), :notice => "タスクを登録しました。"
    else
      redirect_to :action => "new"
    end
  end

  def update
    if @task.update(task_params)
      redirect_to user_tasks_path(@user,@task), :notice => "タスクを登録しました。"
    else
      render :action => "edit"
    end
  end
  
  def destroy
   @task.destroy
   redirect_to user_tasks_path(@user), :alert => "タスクを削除しました。"
# リマインド通知機能実装　テストメール用の設定
   NoticeMailer.sendmail_blog.deliver
  end
  
  def unclosed
# @tasks = Task.where(:status => false)
# @tasks = Task.unclosedをP9-11で以下に変更
   @tasks = @user.tasks.unclosed
   render :action => "index"
  end
  
  def done
# @tasks = Task.update(:status => true)をP9-11で以下に修正
   @task.update(:status => true)
# redirect_to tasks_pathをP9-11で以下に変更
   redirect_to user_tasks_path(@user)
  end
  
  private
  def task_params
    params.require(:task).permit(:name,:deadline,:status)
  end
  
  def find_user
    @user = User.find(params[:user_id])
  end
  
  def find_task
    @task = @user.tasks.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, :only => [:new, :create]
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :birthday,
                                       :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def humanize_date(date)
        date.strftime("%Y年%m月%d日")
    end
    
    def humanize_status(status)
        status ? "完了" : "未完了"
    end
    #STEp11-11で追加
    def link_to_tags(tags)
        tags_link = tags.map do |tag|
          link_to(tag.name, user_tasks_path(@user, :tag => tag.name))
        end
        tags_link.join(", ").html_safe
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div id="header">
    <%= image_tag "logo.png",:size => "116x46",:alt => "ToDo" %>
    <% if current_user %>
       ようこそ <%= link_to current_user.name, current_user %> 様
    <%= link_to "タスク一覧",user_tasks_path(current_user) %>
    <%= link_to "ユーザ一覧",users_path %> |
    <%= link_to "ログアウト",logout_path %> |
    <% else %>
    <%= link_to "ログイン",login_path %> |
    <%= link_to "ユーザ登録",new_user_path %> |
    <% end %>    
    <%= link_to "ホーム",root_path %> |
    <% link_to "このサイトについて",about_path %> |
    <% link_to "練習用",place_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">

 <%= render "layouts/header" %>
 <%= yield %>

</div>
</body>
</html>

app/views/pages/_menu.html.erb
<%= link_to "ホーム",root_path %>

app/views/pages/about.html.erb
<h1>このサイトについて</h1>
<p>ToDoは認証とタグ付け機能をもったリスト管理アプリケーションです。</p>

app/views/pages/index.html.erb
<h1>ToDo アプリケーションへようこそ！</h1>

<%= render "menu" %>

app/views/pages/place.html.erb
<h1>練習用</h1>
<p>このページはRailsのビュー機能の練習用に使用してください。</p>

app/views/tasks/_form.html.erb
<%= form_for([@user, @task]) do |f| %>
 <% if @task.errors.any? %>
  <div id="error_explanation">
   <h2><%= @task.errors.count %> errors.</h2>
   <ul>
    <% @task.errorsfull_messages.each do |msg| %>
     <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
<% end %>
   
 <div class="field">
   <%= f.label :status, 'ステータス' %><br />
   <%= f.radio_button :status, true %> 完了
   <%= f.radio_button :status, false %> 未完了
 </div>
 <div class="field">
   <%= f.label :name, '名前' %><br />
   <%= f.text_field :name %>
 </div>
 <div class="field">
   <%= f.label :deadline, '締め切り' %><br />
   <%= f.date_select :deadline, use_month_numbers: true %>
 </div>
 <%= f.submit "登録" %>
 <% end %>
 

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= render 'form' %>
<%= link_to 'タスク一覧に戻る', user_tasks_path(@user) %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<div id="notice"><%= notice %></div>

<p>
   <%=link_to "新規作成", new_user_task_path(@user) %> |
   <%=link_to "未完了タスク一覧", unclosed_user_tasks_path(@user) %>
</p>

<%= form_tag user_tasks_path(@user), :method => :get do %>
 <%= text_field_tag :name, @name %>
 <%= submit_tag "検索" %>
<% end %>

<table>
    <tr>
         <th>状態</th>
         <th>タスク名</th>
         <th>締め切り</th>

         <th></th>
    </tr>
<% @tasks.each do |task| %>
    <tr>
         <td><%= humanize_status(task.status) %></td>
         <td><%= task.name %></td>
         <td><%= humanize_date(task.deadline) %></td>

         <td>
          <%= link_to "表示", user_task_path(@user,task) %> |
          <%= link_to "編集", edit_user_task_path(@user,task) %> |
          <%= link_to "削除", user_task_path(@user,task),:method => :delete,
                              :data => {:confirm => "本当に削除しますか？"} %> |
          <%= link_to "完了", done_user_task_path(@user,task), :method => :put %>
         </td>
    </tr>
<% end %>
</table>

app/views/tasks/new.html.erb
<h1>タスク作成</h1>
<%= render 'form' %>
<%= link_to 'タスク一覧に戻る', user_tasks_path(@user) %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<div id="notice"><%= notice %></div>

<table>
    <tr>
         <th>状態</th>
         <td><%= humanize_status(@task.status) %></td>
    </tr>
    <tr>
         <th>タスク名</th>
         <td><%= @task.name %></td>
    </tr>
    <tr>
         <th>締切日</th>
         <td><%= humanize_date(@task.deadline) %></td>
    </tr>
    

    
</table>

<p>
    <%= link_to "編集", edit_user_task_path(@user, @task) %> |
    <%= link_to "戻る", user_tasks_path(@user) %> |
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '名前'  %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, 'メールアドレス'  %><br>
    <%= f.text_field :email %>
  </div>
  
  <% if action_name.in? ["new", "create"] %>
    <div class = "field">
      <%= f.label :password, 'パスワード'  %><br />
      <%= f.password_field :password %>
    </div>
    <div class = "field">
      <%= f.label :password_cofirmation, 'パスワード確認'  %><br />
      <%= f.password_field :password_cofirmation %>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :birthday, '生年月日'  %><br>
    <%= f.date_select :birthday, :start_year => 1940,
                                 :end_year => Date.today.year,
                                 :use_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ情報編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザ一覧', @user %> |
<%= link_to '戻る', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザ一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>生年月日</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= humanize_date(user.birthday) %></td>
        <td><%= link_to 'ユーザ詳細', user %></td>
        <td><%= link_to '編集', edit_user_path(user) %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ユーザ登録', new_user_path %>

app/views/users/new.html.erb
<h1>ユーザ登録</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>生年月日:</strong>
  <%= @user.birthday %>
</p>

<%= link_to 'タスク一覧', user_tasks_path(@user) %> |
<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '戻る', users_path %>